name: turing-experiments
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - aiohttp
  - aiosignal
  - appdirs
  - appnope
  - asttokens
  - async-timeout
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - black
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - click
  - colorama
  - comm
  - contourpy
  - cryptography
  - cycler
  - darglint
  - debugpy
  - decorator
  - docker-pycreds
  - et_xmlfile
  - executing
  - fire
  - flake8
  - flake8-black
  - flake8-docstrings
  - fonttools
  - freetype
  - frozenlist
  - gitdb
  - gitpython
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - jedi
  - joblib
  - jpeg
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - lcms2
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libdeflate
  - libffi
  - libgfortran5
  - liblapack
  - libopenblas
  - libpng
  - libprotobuf
  - libsodium
  - libsqlite
  - libtiff
  - libwebp-base
  - libxcb
  - libzlib
  - llvm-openmp
  - matplotlib-base
  - matplotlib-inline
  - mccabe
  - multidict
  - munkres
  - mypy_extensions
  - nest-asyncio
  - numpy
  - openai
  - openjpeg
  - openpyxl
  - openssl
  - packaging
  - pandas
  - pandas-stubs
  - parso
  - pathspec
  - pathtools
  - patsy
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - plotly
  - pooch
  - prompt-toolkit
  - protobuf
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pycodestyle
  - pycparser
  - pydocstyle
  - pyflakes
  - pygments
  - pyopenssl
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - sentry-sdk
  - setproctitle
  - setuptools
  - six
  - smmap
  - snowballstemmer
  - stack_data
  - statsmodels
  - tenacity
  - termcolor
  - threadpoolctl
  - tk
  - tomli
  - tornado
  - tqdm
  - traitlets
  - types-pytz
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wandb
  - wcwidth
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - yarl
  - zeromq
  - zipp
  - zstd
  - libcxx
  - libgfortran
  - pip:
      - ncurses
      - readline